#!/usr/bin/env python3
import os
from PIL import Image

new_dir = "/opt/icons/"

#to print the path of images directory
image_location = os.path.abspath("images")

#iterate through the images directory content
for image in os.listdir("images"):

#to avoid any hidden file the resulted form using listdir()
        if not image.startswith('.'):

#to separate or devide the path of image to root and ext
            new_img = os.path.splitext(image)[0] + '.JPG'
            try:

#as the script isn't inside the images directory so we need to give the absolute path of the selected image
                im = Image.open(image_location + '/' + image)

#use convert('RGB') to avoid OSError: cannot write mode LA as JPEG
                im.rotate(-90).convert('RGB').resize((128,128)).save(new_dir+new_img)
            except:
               print("failed to convert:", image)
